version: '3.7'

networks:
  basnet:
    external: true

services:

  zookeeper1:
    image: zookeeper:3.4.14
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    volumes:
      - data_zookeeper1:/data
      - data_zookeeperlog1:/datalog
    networks:
      - basnet

  solr1:
    image: bioatlas/ala-solrcloud:v0.1
    restart: always
    environment:
      - SOLR_HEAP=12g
      - ZK_HOST=zookeeper1:2181
      - SOLR_HOST=solr1
    volumes:
      - data_solr1:/opt/solr
    networks:
      - basnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == solr-1]

  solr2:
    image: bioatlas/ala-solrcloud:v0.1
    restart: always
    environment:
      - SOLR_HEAP=12g
      - ZK_HOST=zookeeper1:2181
      - SOLR_HOST=solr2
    volumes:
      - data_solr2:/opt/solr
    networks:
      - basnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == solr-2]

  solr3:
    image: bioatlas/ala-solrcloud:v0.1
    restart: always
    environment:
      - SOLR_HEAP=12g
      - ZK_HOST=zookeeper1:2181
      - SOLR_HOST=solr3
    volumes:
      - data_solr3:/opt/solr
    networks:
      - basnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == solr-3]

  solr4:
    image: bioatlas/ala-solrcloud:v0.1
    restart: always
    environment:
      - SOLR_HEAP=12g
      - ZK_HOST=zookeeper1:2181
      - SOLR_HOST=solr4
    volumes:
      - data_solr4:/opt/solr
    networks:
      - basnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == solr-4]

#  create-collection:
#    image: solr:7.7.2-slim
#    environment:
#      - SOLR_HOST=solr1
#    volumes:
#      - ./solrcloud/mycores/biocache:/opt/solr/server/solr/configsets/biocache
#    entrypoint:
#      - "bash"
#      - "-exc"
#      - "wait-for-solr.sh --max-attempts 10 --wait-seconds 5 --solr-url http://$$SOLR_HOST:8983/; 
#         solr zk upconfig -z zookeeper1:2181 -n biocache -d /opt/solr/server/solr/configsets/biocache/conf;
#         solr create -c biocache -p 8983 -d biocache -shards 4 -replicationFactor 1;"
#    networks:
#      - basnet
#    deploy:
#      mode: replicated
#      replicas: 1
#      placement:
#        constraints: [node.hostname == bas-main]

volumes:
  data_zookeeper1:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=beta.bioatlas.se,rw
      device: ":/mnt/datacluster/zookeeper1"
  data_zookeeperlog1:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=beta.bioatlas.se,rw
      device: ":/mnt/datacluster/zookeeperlog1"
  data_solr1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/data/data_solr/solr1"
  data_solr2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/data/data_solr/solr2"
  data_solr3:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/data/data_solr/solr3"
  data_solr4:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/data/data_solr/solr4"
